MP_new/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views as core_view
from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project1.urls')),
    path('', core_view.home, name ='home'),
    path('login/', core_view.Login, name ='login'),
    path('dspprofile/', core_view.dspprofile, name ='dspprofile'),
    path('ioprofile/', core_view.ioprofile, name ='ioprofile'),
    path('logout/', core_view.pagelogout, name ='logout'),
    path('dsp/', include('addcases.urls')),
    path('',include('crimerec.urls')),
    path('investigate/', include('investigate.urls'), name='Investigate'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
]

core/urls.py
# from django.urls import path, include
# from django.conf import settings
# from . import views
# from django.conf.urls.static import static
 
# urlpatterns = [
#          path('', views.home, name ='home'),
# ]

crimerec/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('viewrec/', views.crimerecord, name = 'crimerecord'),
path('details/<str:crid>/', views.criminaldetails, name = 'CriminalDetails'),
]

crimerec/models.py
from django.db import models
from addcases.models import Case

class CriminalRecord(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Not Specified','Not Specified'),
    )
    
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    criminal_id = models.CharField(max_length=15, primary_key=True)
    criminal_firstname = models.CharField(max_length = 100, default='')
    criminal_lastname = models.CharField(max_length = 100, default='')
    birthdate = models.DateField(null=True, blank=True)
    no_of_crimes=models.PositiveSmallIntegerField(default=1)
    
    
class CriminalCase(models.Model):
    criminal_id = models.ForeignKey(CriminalRecord, on_delete = models.CASCADE, default='',related_name='crimcase')
    case_id = models.ForeignKey(Case, on_delete = models.CASCADE, default='')
    
    crime_description = models.TextField()
    sentence_status = models.TextField(max_length = 500)
    crime_punishment = models.TextField()

crimerec/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from crimerec.models import CriminalCase
from crimerec.models import CriminalRecord
from crimerec.filters import CriminalRecordFilter
from addcases.models import Case
from itertools import chain
# from crimerec.filters import CaseFilter

@login_required
def crimerecord(request):
    cr = CriminalRecord.objects.all()
    cc = CriminalCase.objects.all()
    myFilter = CriminalRecordFilter(request.GET, queryset=cr)
    res= []
    
    cr=myFilter.qs
    # [res.append(x) for x in cr if x not in res]

    # cr=mynewFilter.qs
    context = {
            'cr': cr,
            'cc':cc,
            'myFilter':myFilter,
            # 'mynewFilter':mynewFilter
        }
    return render(request, 'crimerec/criminalrec.html',context)

@login_required
def criminaldetails(request,crid):
    
    cr = CriminalRecord.objects.filter(criminal_id = crid).first()
    cc = CriminalCase.objects.filter(criminal_id= crid)
    context = {
            'cr': cr,
            'cc':cc
        }
    return render(request, 'crimerec/criminaldet.html',context)

crimerec/templates/crimerec/criminaldet.html
{% extends "project1/base.html" %}
{% load static %}

{% block styles %}

{% endblock %}
{% block title %}
Criminal Record
{% endblock title %}
{% block content %}
<div>
<nav class="navbar navbar-expand-lg navbar-dark  p-3">


        <a class="navbar-brand" mx-3 px-4" href="#">Einvestigate</a>
     
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav   mt-2 mt-lg-0 ml-auto ">
      <li class="nav-item ">
        <a class="nav-link  mx-3 px-4" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link  mx-3 px-4" href="{% url 'dspprofile' %}">Profile</a>
      </li>
      
      <li class="nav-item ">
        <a class="nav-link mx-3" href="{% url 'Addcase' %}">Add Case</a>
      </li>
     
      <li class="nav-item">
        <a class="nav-link  mx-3" href="{% url 'crimerecord' %}">View Criminal Records</a>
      </li>
      
      <li class="nav-item mx-3">
    {% if user.is_authenticated %}
 
<a  class="nav-link" href="{% url 'logout' %}">Logout</a>
{% else %}
  
  <a class="nav-link" href="{% url 'login' %}">Login</a>
{% endif %}
</li>
     
    </ul>
       
    
    </div>
  </nav>
   </div> 
   
   <table class="table table-bordered table-hover ">
   <thead>
    <tr class="text-center" >
    <th colspan="2">PERSONAL DETAILS</th>
   </tr>
    </thead>
   <tbody>   
   <tr> 
   <td>CRIMINAL ID: {{ cr.criminal_id }}</td>
   <td>NO. OF CRIMES: {{ cr.no_of_crimes }}</td></tr>
   <tr>
   <tr>
   <td >FIRST NAME: {{ cr.criminal_firstname }}</td>
   <td>LAST NAME: {{ cr.criminal_lastname }}</td>
   
   </tr>
   <tr>
   <td >BIRTHDATE: {{ cr.birthdate }}</td>
   <td>GENDER: {{ cr.gender }}</td>
   
   </tr>

   </tbody>
   </table>
   
   {%for c in cc%}
   <table class="table table-bordered table-hover ">
   <thead>
    <tr class="text-center" >
    <th colspan="2">CASE ID: {{ c.case_id.case_id }}</th>
   </tr>
    </thead>
   <tbody>   
   <tr> 
   <td>CASE DESCRIPTION : {{ c.crime_description }}</td>
   </tr>
   <tr>
   <tr>
   <td >CRIME CATEGORY: {{ c.case_id.case_category }}</td>
   <td>CRIME DATE: {{ c.case_id.crime_date }}</td>
   
   </tr>
   <tr>
   <td >CRIME LOCATION: {{ c.case_id.crime_location }}</td>
   <td>CRIME DISTRICT: {{ c.case_id.crime_district }}</td>
   
   </tr>
   <tr>
   <td colspan="2">CRIME PUNSISHMENT: {{ c.crime_punishment }}</td>
   </tr>
   <tr>
   <td colspan="2">SENTENCE STATUS: {{ c.sentence_status }}</td>
   </tr>
   <tr>
   <td >IO NAME: {{ c.case_id.case_io.user.first_name }} {{ c.case_id.case_io.user.last_name }}</td>
   <td>IO EMAIL: {{ c.case_id.case_io.user.email }}</td>
   
   </tr>
   </tbody>
   </table>
{%endfor%}
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block js %}{% endblock%}
{% endblock content %}

crimerec/templates/crimerec/criminalrec.html
{% extends "project1/base.html" %}
{% load static %}

{% block styles %}
#id_criminal_firstname, #id_criminal_lastname{
    width: 100%;
    
}

.filtercon
{
  width:70%;
  margin-bottom: 20px;
  {% comment %} padding:20px; {% endcomment %}

}
table.test td {

  padding: 12px 12px 12px 12px;
}
.filtertable
{
  margin:auto;
}
.filtercss
{
  
  padding-right:40px;
  width:65%;
}
.btn{
  background-color:#5e6ab0;
  color:white;
}
{% endblock %}
{% block title %}
Criminal Record
{% endblock title %}
{% block content %}
<div>
<nav class="navbar navbar-expand-lg navbar-dark  p-3">


        <a class="navbar-brand" mx-3 px-4" href="#">Einvestigate</a>
     
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav   mt-2 mt-lg-0 ml-auto ">
      <li class="nav-item ">
        <a class="nav-link  mx-3 px-4" href="{% url 'home' %}">Home</a>
      </li>
      {% if user.profile.role == 2 %}
      <li class="nav-item ">
        <a class="nav-link  mx-3 px-4" href="{% url 'dspprofile' %}">Profile</a>
      </li>
      {% endif %}
      {% if user.profile.role == 3 %}
      <li class="nav-item ">
        <a class="nav-link  mx-3 px-4" href="{% url 'ioprofile' %}">Profile</a>
      </li>
      {% endif %}
      
      
      <li class="nav-item">
        <a class="nav-link active mx-3" href="{% url 'crimerecord' %}">View Criminal Records</a>
      </li>
      
      <li class="nav-item mx-3">
    {% if user.is_authenticated %}
 
<a  class="nav-link" href="{% url 'logout' %}">Logout</a>
{% else %}
  
  <a class="nav-link" href="{% url 'login' %}">Login</a>
{% endif %}
</li>
     
    </ul>
       
    
    </div>
  </nav>
   </div> 
   <br>
  <br>
  <div class="primary">
  <div class="container filtercon">
    <div class="row">
      <div class="col-xs-6 filtercss">
  
        <div class="filter-menu">
          <form method="get" id="formid">
            <div class="panel panel-default">
      

              <div class="panel-body">
                <div class="panel-group" id="filter-menu" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne" style="text-align:center;">
                    
                      <a class="panel-title accordion-toggle" role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        <button class="btn" style="width:100%;margin-bottom:15px;">
                        FILTER BY
                         </button>
                      </a><!-- /.panel-title -->
                     
                    </div><!-- /.panel-heading -->
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                      <table class="filtertable">
                      <tr>
                        <td>{{myFilter.form.criminal_firstname.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.criminal_firstname}}</td>
                        </tr>
                        <tr>
                        <td>{{myFilter.form.criminal_lastname.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.criminal_lastname}}</td>
                         </tr>
                        <tr>
                       <td>{{myFilter.form.gender.label_tag}}</td>
                       <td colspan="2">{{myFilter.form.gender}}</td>
                        </tr>
                       <tr>
                        <td>{{myFilter.form.crimcase__criminal_id.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.crimcase__criminal_id}}</td>
                         </tr>
                        <tr>
                        <td>{{myFilter.form.crimcase__case_id.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.crimcase__case_id}}</td>
                         </tr>
                        <tr>
                        <td>{{myFilter.form.crime_district.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.crime_district}}</td>
                         </tr>
                        <tr>
                        <td>{{myFilter.form.case_category.label_tag}}</td>
                        <td colspan="2">{{myFilter.form.case_category}}</td>
                         </tr>
                      </table>
                      </div><!-- /.panel-body -->
                    </div><!-- /.panel-collapse -->
                  </div><!-- /.panel -->

                  
                  
                </div><!-- /.panel-group -->
              </div><!-- /.panel-body -->
             
            </div><!-- /.panel -->
            
          
        </div><!-- /.filter-menu --> 
    </div>  
        <div class="col-xs-3" style="margin-right:40px;"><button class="btn" type="submit">APPLY FILTER</button></div>
        
        </form>   
        <div class="col-xs-3">
         
        <a  href="{% url 'crimerecord' %}">
        <button class="btn ">
        CLEAR ALL
        </button>
        </a>
        
        </div>  
      </div> <!-- row -->

      
      
      <!-- -------------------------------------------------- -->
      
      
    
  </div><!-- /.container -->
</div><!-- /.primary -->

   <table class="table table-bordered table-hover ">
    <thead>
    <tr class="text-center">
    <th>Criminal ID</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Gender</th>
    <th>Birth date</th>
    <th>No of Crimes</th>
    
  </tr>
    </thead>
    <tbody>   

   
   {% for cr in  cr %}
  
   <tr class="clickable text-center" onclick="window.location='{% url 'CriminalDetails' cr.criminal_id %}'">
       <td> {{ cr.criminal_id }} </td>
       <td> {{ cr.criminal_firstname }} </td>
       <td> {{ cr.criminal_lastname }} </td>
       <td> {{ cr.gender}} </td>
       <td> {{ cr.birthdate}} </td>
       <td> {{ cr.no_of_crimes }} </td>
      
       
    </tr>
  {% endfor %}
  </tbody>
   </table>
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block js %}{% endblock%}
{% endblock content %}